2022-05-31 15:18:12,185 INFO: My Blog startup [in /Users/vladimirbankovic/Desktop/my_blog/app/__init__.py:45]
2022-05-31 15:20:07,733 ERROR: Exception on /reset_password_request [POST] [in /Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/vladimirbankovic/Desktop/my_blog/app/routes.py", line 175, in reset_password_request
    send_password_reset_email(user)
  File "/Users/vladimirbankovic/Desktop/my_blog/app/email.py", line 24, in send_password_reset_email
    html_body=render_template('email/reset_password.html',
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/reset_password.html
2022-05-31 15:22:35,741 INFO: My Blog startup [in /Users/vladimirbankovic/Desktop/my_blog/app/__init__.py:45]
2022-05-31 15:22:41,708 ERROR: Exception on /reset_password_request [POST] [in /Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/vladimirbankovic/Desktop/my_blog/app/routes.py", line 175, in reset_password_request
    send_password_reset_email(user)
  File "/Users/vladimirbankovic/Desktop/my_blog/app/email.py", line 24, in send_password_reset_email
    html_body=render_template('email/reset_password.html',
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/reset_password.html
2022-05-31 15:24:45,759 INFO: My Blog startup [in /Users/vladimirbankovic/Desktop/my_blog/app/__init__.py:45]
2022-05-31 15:24:51,605 ERROR: Exception on /reset_password_request [POST] [in /Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/vladimirbankovic/Desktop/my_blog/app/routes.py", line 175, in reset_password_request
    send_password_reset_email(user)
  File "/Users/vladimirbankovic/Desktop/my_blog/app/email.py", line 19, in send_password_reset_email
    send_email('[My Blog] Reset Your Password',
TypeError: send_email() got multiple values for argument 'sender'
2022-05-31 15:35:16,083 ERROR: Exception on /reset_password_request [POST] [in /Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/vladimirbankovic/Desktop/my_blog/app/routes.py", line 175, in reset_password_request
    send_password_reset_email(user)
  File "/Users/vladimirbankovic/Desktop/my_blog/app/email.py", line 19, in send_password_reset_email
    send_email('[My Blog] Reset Your Password',
TypeError: send_email() got multiple values for argument 'sender'
2022-05-31 15:35:39,192 ERROR: Exception on /reset_password_request [POST] [in /Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vladimirbankovic/Desktop/my_blog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/vladimirbankovic/Desktop/my_blog/app/routes.py", line 175, in reset_password_request
    send_password_reset_email(user)
  File "/Users/vladimirbankovic/Desktop/my_blog/app/email.py", line 19, in send_password_reset_email
    send_email('[My Blog] Reset Your Password',
TypeError: send_email() got multiple values for argument 'sender'
